=== ashwinijai/DBTransformer/src/main/resources/schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "ColumnProperties" : {
      "type" : "object",
      "properties" : {
        "columnName" : {
          "type" : "string",
          "minLength" : 1
        },
        "dataType" : {
          "type" : "string",
          "minLength" : 1,
          "pattern" : "VARCHAR|NUMBER|CLOB"
        },
        "isMandatory" : {
          "type" : "string",
          "minLength" : 1,
          "pattern" : "true|false"
        },
        "size" : {
          "type" : "integer"
        }
      },
      "required" : [ "columnName", "dataType", "isMandatory", "size" ]
    },
    "DBProperties" : {
      "type" : "object",
      "properties" : {
        "dbType" : {
          "type" : "string",
          "minLength" : 1,
          "pattern" : "ORACLE|H2"
        },
        "password" : {
          "type" : "string",
          "minLength" : 1
        },
        "schemaName" : {
          "type" : "string",
          "minLength" : 1
        },
        "tableName" : {
          "type" : "string",
          "minLength" : 1
        },
        "url" : {
          "type" : "string",
          "minLength" : 1
        },
        "userName" : {
          "type" : "string",
          "minLength" : 1
        },
        "whereClause" : {
          "type" : "string"
        }
      },
      "required" : [ "dbType", "password", "schemaName", "tableName", "url", "userName" ]
    }
  },
  "type" : "object",
  "properties" : {
    "dbMapping" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "sourceColumn" : {
            "type" : "string",
            "minLength" : 1
          },
          "targetColumn" : {
            "type" : "string",
            "minLength" : 1
          }
        },
        "required" : [ "sourceColumn", "targetColumn" ]
      }
    },
    "sourceDb" : {
      "$ref" : "#/$defs/DBProperties"
    },
    "sourceProperties" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/ColumnProperties"
      }
    },
    "targetDb" : {
      "$ref" : "#/$defs/DBProperties"
    },
    "targetProperties" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/ColumnProperties"
      }
    }
  }
}

=== ashwinijai/DBTransformer/src/main/resources/request.json
{
  "sourceDb": {
    "url": "jdbc:h2:file:/Users/ashwinijayaraman/Downloads/Practice/DB;AUTO_SERVER=TRUE;SCHEMA=ABC",
    "userName": "sa",
    "password": "password",
    "tableName": "Employee",
    "schemaName": "ABC",
    "dbType": "H2"
  },
  "targetDb": {
    "url": "jdbc:h2:file:/Users/ashwinijayaraman/Downloads/Practice/DB1;AUTO_SERVER=TRUE;SCHEMA=ABC",
    "userName": "sa",
    "password": "password",
    "tableName": "Employee",
    "schemaName": "ABC",
    "dbType": "H2"
  },
  "sourceProperties": [
    {
      "columnName": "EMP_ID",
      "dataType": "NUMBER",
      "size": 10,
      "isMandatory": "true"
    },
    {
      "columnName": "EMP_NAME",
      "dataType": "VARCHAR",
      "size": 10,
      "isMandatory": "false"
    },
    {
      "columnName": "CITY",
      "dataType": "VARCHAR",
      "size": 10,
      "isMandatory": "false"
    },
    {
      "columnName": "DEPT",
      "dataType": "VARCHAR",
      "size": 10,
      "isMandatory": "false"
    }
  ],
  "targetProperties": [
    {
      "columnName": "EMP_ID",
      "dataType": "NUMBER",
      "size": 10,
      "isMandatory": "true"
    },
    {
      "columnName": "EMP_NAME",
      "dataType": "VARCHAR",
      "size": 15,
      "isMandatory": "false"
    },
    {
      "columnName": "CITY",
      "dataType": "VARCHAR",
      "size": 10,
      "isMandatory": "false"
    },
    {
      "columnName": "DEPT",
      "dataType": "VARCHAR",
      "size": 10,
      "isMandatory": "false"
    }
  ],
  "dbMapping": [
    {
      "sourceColumn": "EMP_ID",
      "targetColumn": "EMP_ID"
    },
    {
      "sourceColumn": "EMP_NAME",
      "targetColumn": "EMP_NAME"
    },
    {
      "sourceColumn": "CITY",
      "targetColumn": "CITY"
    },
    {
      "sourceColumn": "DEPT",
      "targetColumn": "DEPT"
    }
  ]
}
